spring.application.name=cotizador-backend
server.port=8080


spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=public

spring.jpa.properties.hibernate.format_sql=false
# Evita N+1 en colecciones Lazy sin fetch explícito
spring.jpa.open-in-view=false

# spring.sql.init.mode=always primer deploy, luego cambiar a never para no re-ejecutar el seed

spring.sql.init.mode=never
spring.jpa.defer-datasource-initialization=true


jwt.secret=${JWT_SECRET}
# 1 hora en ms
jwt.expiration-ms=3600000

# ── Jackson ────────────────────────────────────────────────────
# Evitar que campos null aparezcan en las respuestas JSON
spring.jackson.default-property-inclusion=non_null
# Formato ISO 8601 para fechas (no timestamps numéricos)
spring.jackson.serialization.write-dates-as-timestamps=false

# ── Logs ───────────────────────────────────────────────────────
logging.level.pe.com.polyline=INFO
logging.level.org.springframework.security=WARN

# API KEYS

cloudinary.cloud-name=${CLOUD_NAME}
cloudinary.api-key=${CLOUD_KEY}
cloudinary.api-secret=${CLOUD_SECRET}

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB


